### ISSUE TITLE
在外链中播放后 回到主站播放出错了，请点击切换到原版Flash播放器

### ISSUE THREAD

**Issue by rainning123** [gooyie/userscript-iqiyi-player-switch#13]
从外链中点击播放器右下角爱奇艺图标返回主站后失效
外链中仍能使用 
但是主站：播放出错了，请点击切换到原版Flash播放器 
错误代码：(P2P200)

浏览器是chrome 版本 59.0.3071.115（正式版本） （64 位）
外链是 http://www.zybus.com/ltyy/20160410.html

在我关闭adblock plus 规则 EasyList China+EasyList 后又能重新使用

**Comment by gooyie** [comment]
还不支持外链  http://www.zybus.com/ltyy/20160410.html
播放器右下角有爱奇艺图标的是flash播放器。

错误代码：(P2P200) 是网络出错，是EasyList China+EasyList 里的规则  `/\:\/\/([0-9]{1,3}\.){3}[0-9]{1,3}/$third-party,xmlhttprequest` 干的“好事”。
现在这条规则已被禁用，更新规则就可以了。

**Comment by gooyie** [comment]
外链已添加  6889f3e4a32f772e6982435fb199890f0d364cc2

**Comment by rainning123** [comment]
OK 辛苦了
