### ISSUE TITLE
【问题】插件脚本不显示html5播放器

### ISSUE THREAD

**Issue by misybing** [gooyie/userscript-iqiyi-player-switch#16]
用Tampermonkey装的，打开爱奇艺，插件不显示html5播放器，和官方介绍的不一样。
实际的：
<img src="http://wx3.sinaimg.cn/mw690/65db906egy1flxsp5tfrzj20ab04cgls.jpg">

官方介绍的：
<img src="http://wx4.sinaimg.cn/mw690/65db906egy1flxsp0vl37j20mx09bmx5.jpg">

**Comment by gooyie** [comment]
F12打开控制台看看有没有 `registered menu.`，如下图所示。

![2017-12-03_200656](https://user-images.githubusercontent.com/25021141/33525183-b82d016a-d865-11e7-8eb1-383249a5c466.png)
