### ISSUE TITLE
iqiyi现在用不了html5了

### ISSUE THREAD

**Issue by GithubUsername3** [gooyie/userscript-iqiyi-player-switch#21]
开本脚本就无法使用html5，只能用flash，关脚本后才能使用html5，不过就有广告

**Comment by gooyie** [comment]
我刚试了，没问题的。
可能和其它脚本或扩展冲突了，你自己排查下。

**Comment by gam2046** [comment]
![image](https://user-images.githubusercontent.com/1665403/37462555-615454d8-288d-11e8-9fc0-8e252e3769cf.png)

目前一直无法播放，而关闭脚本后使用iqiyi自己的播放器则无问题

**Comment by gooyie** [comment]
我没问题
![2018-03-15_212533](https://user-images.githubusercontent.com/25021141/37465960-89716730-2897-11e8-8a45-4e2443750fd0.png)

还有，脚本用的就是iqiyi的播放器。

**Comment by GithubUsername3** [comment]
chrome、qq browser都有同样疸，firefox新建profile还是同样，附图是firefox信息

![iqiyi websocket 403 405](https://user-images.githubusercontent.com/29504818/37472799-e4fdb436-28a7-11e8-8038-c36aa0c4dbda.png)

![iqiyi websocket](https://user-images.githubusercontent.com/29504818/37472802-e53444ce-28a7-11e8-9a1d-8616151f7386.png)

**Comment by gooyie** [comment]
好吧，有些地区的CDN还不支持 WebSocket。
我把 WebSocket 放到播放器的设置里，默认不启用。

**Comment by GithubUsername3** [comment]
现在好了
