### ISSUE TITLE
免会员看1080P+有没有额外条件？

### ISSUE THREAD

**Issue by ivysrono** [gooyie/userscript-iqiyi-player-switch#3]
平时用的Firefox但只能看到高清，于是专门去开了Chrome，也只能看到720P，1080P还是要提示会员。

需要登录？

**Comment by gooyie** [comment]
现在需要登录

**Comment by ivysrono** [comment]
1.2.0可以了。
Firefox载入失败还是极大概率事件。

**Comment by ivysrono** [comment]
顺便一问，qq那的1080限制能破解不？

**Comment by gooyie** [comment]
you-get 可以下载到1080P视频， 应该可以的。

**Comment by ivysrono** [comment]
没有看到qqh5的github，只好在这说了。
不支持：
https://view.inews.qq.com/a/TEC2016121302749602
