### ISSUE TITLE
视频最后几秒一直重复

### ISSUE THREAD

**Issue by GoogleGFW** [gooyie/userscript-iqiyi-player-switch#4]
最后几秒一直重复回放，是iqiyi的问题还是脚本的BUG，谢谢。

**Comment by gooyie** [comment]
脚本没有干预播放。

以前我也出现过播放回跳，是视频缓冲出错导致的。
那时控制台出现了很多视频加载错误， 可现在已经没出现过。
可能是你的网络不好或浏览器版本比较低对新的api支持不好。

**Comment by GoogleGFW** [comment]
确实是Chromium内核版本旧了的缘故。
因为应用商店的缘故习惯用QQ浏览器替代Chrome,它的最新内核53。
下载Chrome更新到57可以正常跳集连播了。
感谢。
