### ISSUE TITLE
1.5.1 无法切换到 html5 模式

### ISSUE THREAD

**Issue by ivysrono** [gooyie/userscript-iqiyi-player-switch#6]
Fx54b3/4
GM3.11

1.4.0 可用
1.5.1 在 GM 命令菜单里都找不到了，保持 flash，也就没法测试更多了。

**Comment by gooyie** [comment]
油猴因沙箱问题是用不了的。
之前的能用的也就注册菜单和cookie操作而已。

现在为了让firefox与edge也可以播放f4v，多用了 fetch stream polyfill 与WebRTC adapter 而已。
油猴就”无声无息“的彻底失效了。

**Comment by ivysrono** [comment]
Firefox 上的 Tampermonkey 实在是不好用，Violentmonkey 又没有过审，为之奈何？
